version: "3"

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  meterialrequest:
    build: .
    container_name: meterialrequest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
